=== setareA/polito-DSP/lab01/task_schema.json
{
    "$schema":"http://json-schema.org/draft-07/schema",
    "$id": "http://www.my-schema.com/task_schema.json",
    "title": "Task",
    "description": "json schema for task object",
    "additionalProperties": false,
    "properties": {
        "$schema":{
            "type":"string",
            "description": "path to the json schema to validate the json file"
        },
        "id":{
            "type": "integer"
        },
        "description":{
            "type":"string",
            "maxLength": 160
        },
        "important":{
            "type":"boolean", 
            "default": false
        },
        "private":{
            "type":"string",
            "default":true
        },
        "projects":{
            "type":"array",
            "items": {
                "type":"string",
                "enum": ["Personal", "WA1_Project", "WA2_Project", "DSP_Project"]
            }, "uniqueItems": true
        }, "deadline":{
                "type":"string",
                "format": "date-time",
                "pattern": "^((202[1-9])|(20[3-9][0-9])|(2[1-9][0-9][0-9])|([3-9][0-9][0-9][0-9]))-"
        },
        "completed":{
            "type":"boolean",
            "default": false
        },
        "owner":{
            "$ref": "user_schema.json"
        },
        "assignedTo":{
            "type":"array",
            "items":{
                "$ref": "user_schema.json"
            }
        }
    },
    "required": ["id", "description"]
}

=== setareA/polito-DSP/lab01/task1.json
{
    "$schema": "./task_schema.json",
    "id": 1,
    "description": "simple task",
    "deadline": "2021-12-04T00:00:00Z",
    "owner": {
        "id": 1,
        "name": "sara",
        "email": "sara@polito.it"
    },
    "assignedTo": [
        {
          "id": 2,
          "name": "setare",
          "email": "setare@gmail.com"
        },
        {
            "id": 3,
            "name": "sare",
            "email": "sara@gmail.com"
        }
    ]
}
